name: to_do_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Get
  get_storage: ^2.1.1
  get: ^4.7.2

  cached_network_image: ^3.3.1
  cloud_firestore: ^5.6.4
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  dio_cache_interceptor: ^3.5.0
  dio: ^5.4.3+1
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.0+4
  flutter_dotenv: ^5.2.0

dev_dependencies: 
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true
  generate: true
  assets:
    - .env
  